apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dropall
  name: dropall
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: dropall
    resources: {}
    securityContext:
      runAsUser: 2000
      capabilities:
        drop:
          - all
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
